spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Rajkumar-Lakshman/spring-cloud-config-server 
    
server:
  port: 9196
  
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
  
      